# Site settings
title: Stan Zonov
email: hello at szonov.com


include: ['courses']
include: ['games']


# Build settings
markdown: kramdown
permalink: pretty

url: "https://szonov.com"


gallerytags:
  dir: photos
  galleries:
   - winnipeg
   - powell_river
   - russia
   - screaming_heads
